Vagrant.configure('2') do |config|
  # You should use VMware (Workstation or Fusion) or KVM to run this box
  # because VirtualBox doesn't support nested virtualization, which
  # is required to run KVM (https://www.virtualbox.org/ticket/4032)
  config.vm.provider :vmware_fusion do |vmware, override|
    override.vm.box = 'vagrant-kvm'
    override.vm.box_url = 'https://s3.amazonaws.com/life360-vagrant/raring64.box'
    vmware.vmx['vhv.enable'] = true # nested virtualization
  end

  # Please add /etc/modprobe.d/kvm.conf that contains
  #
  #   options kvm-intel nested=1
  #   options kvm-amd   nested=1
  #
  # to use KVM with nested virtulization support.
  # The box here is mostly same image as vmwares but adding nfs client
  config.vm.provider :kvm do |kvm, override|
    override.vm.box     = 'vagrant-kvm'
    override.vm.box_url = 'https://s3-ap-northeast-1.amazonaws.com/miurahr-public/vagrant-kvm.box'
  end

  config.vm.provision :shell, inline: <<-SH
    set -x

    export DEBIAN_FRONTEND=noninteractive

    ## when use apt-cacher
    #echo 'Acquire::http::Proxy "http://192.168.123.1:3142";' > /tmp/01proxy
    #sudo mv /tmp/01proxy /etc/apt/apt.conf.d/01proxy

    sudo apt-get update

    sudo apt-get install -y ruby2.0-dev
    ## NOTE qemu-bin should be installed before libvirt-bin
    sudo apt-get install -y qemu qemu-kvm
    sudo apt-get install -y libvirt-dev libvirt-bin
    sudo apt-get install -y git
    sudo apt-get install -y nfs-kernel-server
    sudo apt-get install -y bsdtar
    sudo apt-get install -y libxml2-dev libxslt-dev
    sudo apt-get install -qq redir

    [[ `sudo gem list | grep bundler` ]] || sudo gem install --version '~> 1.5.2' bundler
  SH
end
