Vagrant.configure('2') do |config|
  # You should use VMware (Workstation or Fusion) or KVM to run this box
  # because VirtualBox doesn't support nested virtualization, which
  # is required to run KVM (https://www.virtualbox.org/ticket/4032)
  config.vm.provider :vmware_fusion do |vmware, override|
    override.vm.box = 'vagrant-kvm'
    override.vm.box_url = 'https://s3.amazonaws.com/life360-vagrant/raring64.box'
    vmware.vmx['vhv.enable'] = true # nested virtualization
  end

  # Please add /etc/modprobe.d/kvm.conf that contains
  #
  #   options kvm-intel nested=1
  #   options kvm-amd   nested=1
  #
  # to use KVM with nested virtulization support.
  config.vm.provider :kvm do |kvm, override|
    kvm.memory_size     = '512m'
    override.vm.box     = 'vagrant-kvm'
    override.vm.box_url = 'https://vagrant-kvm-boxes.s3.amazonaws.com/vagrant-kvm.box'
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.auto_detect = true
  end

  config.vm.provision :shell, inline: <<-SH
    set -x

    export DEBIAN_FRONTEND=noninteractive

    ## When you use precise or saucy
    ## No need for trusty(test box for kvm)
    #sudo apt-get update
    #sudo apt-get install -qq python-software-properties
    #sudo add-apt-repository ppa:miurahr/vagrant-devel

    sudo apt-get install -y ruby2.0-dev
    ## NOTE qemu-bin should be installed before libvirt-bin
    sudo apt-get install -y qemu qemu-kvm
    sudo apt-get install -y libvirt-dev libvirt-bin
    sudo apt-get install -y git
    sudo apt-get install -y nfs-kernel-server
    sudo apt-get install -y bsdtar
    sudo apt-get install -y libxml2-dev libxslt-dev
    sudo apt-get install -qq redir

    sudo usermod vagrant -a -G libvirtd

    # vagrant 1.4 and after only support ruby2.0
    sudo update-alternatives --quiet --set ruby /usr/bin/ruby2.0
    sudo update-alternatives --quiet --set gem /usr/bin/gem2.0

    # force libvirt to recognize qemu
    sudo service libvirtd-bin restart

    # work around for kernel bug
    sudo apt-get install -qq apparmor-utils
    sudo aa-complain /usr/lib/libvirt/virt-aa-helper

    [[ `sudo gem list | grep bundler` ]] || sudo gem install --version '~> 1.5.2' bundler

    ## Now you can do
    #cd /vagrant
    #bundle exec rake box:add
    #bundle exec rake box:prepare

  SH
end
